[book]
title = "Rust Design Patterns"
authors = ["the rust-unofficial authors", "vlwkaos(translator)"]
description = "A catalogue of Rust design patterns, anti-patterns and idioms"
language = "ko"
multilingual = false
src = "."

[build]
create-missing = false

[rust]
edition = "2018"

[output.html]
default-theme = "rust"
additional-css = ["typography.css"]
git-repository-url = "https://github.com/vlwkaos/rust-patterns-kr"
git-repository-icon = "fa-github"

# [output.linkcheck]  # enable the "mdbook-linkcheck" renderer, disabled due to gh-actions
